services:
  web:
    image: node:20-bookworm-slim
    container_name: doeshing-one-dev
    working_dir: /app
    command: sh -c "apt-get update && apt-get install -y openssl ca-certificates && npm install && npx prisma generate && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - path: .env
        required: false
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      WATCHPACK_POLLING: "true"
    profiles: ["dev"]

  app:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
        - DIRECT_URL=${DIRECT_URL}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    image: doeshing-one:latest
    env_file:
      - path: .env
        required: false
    environment:
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped
    profiles: ["prod"]

volumes:
  node_modules:
